Updates

diff --git a/files/opt/chia/bin/uploadplots b/files/opt/chia/bin/uploadplots
--- a/files/opt/chia/bin/uploadplots
+++ b/files/opt/chia/bin/uploadplots
@@ -56,9 +56,15 @@ pushd ${sync_dir} >> /dev/null
     sync_dst=`ssh ${sync_to} ezplot plotdst`
     # Copy with scp so we can see the rate at which we copy.
     echo "[`date`] transfering plot: ${file} => ${sync_dst}"
-    rsync -avhp -e "ssh -i ~/.ssh/id_rsa" --remove-source-files \
-      ${file} ${sync_to}:${sync_dst}
-    echo "[`date`] transfer complete: ${file} => ${sync_dst}"
+
+    # Make sure the remote directory exists.
+    ssh -i ~/.ssh/id_rsa mkdir -p ${sync_dst} \
+      || echo "Failed to create destination directory: ${sync_dst}" \ &&
+    (
+      rsync -avhp -e "ssh -i ~/.ssh/id_rsa" --remove-source-files ${file} ${sync_to}:${sync_dst} \
+      && \
+      echo "[`date`] transfer complete: ${file} => ${sync_dst}" \
+    )
   done
 
   # Follow up with rsync to verify the transfer and clean out the
