Updates

diff --git a/files/opt/chia/bin/uploadplots b/files/opt/chia/bin/uploadplots
--- a/files/opt/chia/bin/uploadplots
+++ b/files/opt/chia/bin/uploadplots
@@ -58,13 +58,12 @@ pushd ${sync_dir} >> /dev/null
     echo "[`date`] transfering plot: ${file} => ${sync_dst}"
 
     # Make sure the remote directory exists.
-    ssh -i ~/.ssh/id_rsa mkdir -p ${sync_dst} \
-      || echo "Failed to create destination directory: ${sync_dst}" \ &&
-    (
-      rsync -avhp -e "ssh -i ~/.ssh/id_rsa" --remove-source-files ${file} ${sync_to}:${sync_dst} \
-      && \
-      echo "[`date`] transfer complete: ${file} => ${sync_dst}" \
-    )
+    ssh -i ~/.ssh/id_rsa ${sync_to} mkdir -p ${sync_dst} \
+      || echo "Failed to create destination directory: ${sync_dst}";
+
+    rsync -avhp -e "ssh -i ~/.ssh/id_rsa" --remove-source-files ${file} ${sync_to}:${sync_dst} \
+      && echo "[`date`] transfer complete: ${file} => ${sync_dst}" \
+      || echo "[`date`] transfer failed: ${file} => ${sync_dst}"
   done
 
   # Follow up with rsync to verify the transfer and clean out the
